name: schedule
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  script:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        url:
          - 'https://reserve.tokyodisneyresort.jp/sp/showrestaurant/search/?pageFromDiv=1&useDate=20241015&adultNum=3&childNum=3&parkDiv=5&restaurantNameCd=&childAgeInform=03%7C03%7C03%7C&wheelchairCount=0&stretcherCount=0&freeword=&showWay=&reservationStatus=1'
    steps:
      - uses: actions/checkout@v3
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: install dependencies
        run: npm ci
      - name: run script
        run: npm run start
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          TARGET_URL: ${{ matrix.url }}
