name: schedule
on:
  schedule:
    # - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  script:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        url:
          - 'https://reserve.tokyodisneyresort.jp/sp/restaurant/list/?useDate=20240522&mealDivInform=&adultNum=4&childNum=2&childAgeInform=02%7C02%7C&restaurantTypeInform=4&restaurantNameCd=&wheelchairCount=0&stretcherCount=0&showWay=&reservationStatus=1&beforeUrl=https%3A%2F%2Freserve.tokyodisneyresort.jp%2Fsp%2Frestaurant%2Flist%2F%3FuseDate%3D20240522%26mealDivInform%3D%26adultNum%3D4%26childNum%3D2%26childAgeInform%3D02%257C02%257C%26restaurantTypeInform%3D%26restaurantNameCd%3D%26wheelchairCount%3D0%26stretcherCount%3D0%26showWay%3D%26reservationStatus%3D1%26wayBack%3D&wayBack='
          - 'https://reserve.tokyodisneyresort.jp/sp/showrestaurant/list/?useDate=20240522&adultNum=4&childNum=2&childAgeInform=02%7C02%7C&parkDiv=4&restaurantNameCd=&wheelchairCount=0&stretcherCount=0&showWay=&reservationStatus=&beforeUrl=https%3A%2F%2Freserve.tokyodisneyresort.jp%2Fsp%2Ftop%2F&wayBack='
    steps:
      - uses: actions/checkout@v3
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: install dependencies
        run: npm ci
      - name: run script
        run: npm run start
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          TARGET_URL: ${{ matrix.url }}
