name: schedule
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  script:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        url:
          - 'https://reserve.tokyodisneyresort.jp/restaurant/search/?useDate=20240718&adultNum=2&childNum=1&childAgeInform=02%7C&restaurantType%5B0%5D=4&restaurantType%5B4%5D=1&nameCd=&wheelchairCount=0&stretcherCount=0&keyword=&reservationStatus=1'
    steps:
      - uses: actions/checkout@v3
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: install dependencies
        run: npm ci
      - name: run script
        run: npm run start
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          TARGET_URL: ${{ matrix.url }}
